database:
  type: sqlite

  mysql:
    host: localhost
    port: 3306
    database: ezpunishments
    username: root
    password: ""
    pool-size: 10

  mongodb:
    uri: mongodb://localhost:27017
    database: ezpunishments
    collection: punishments
